#服务器端口
server:
  port: 80
#配置数据源
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.242.135:3306/little_chat?serverTimezone=Asia/Shanghai&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: riverwind
  redis:
    password: riverwind
    port: 6379
    host: 192.168.242.135
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms

